#!/usr/bin/env bash
##Print while loop

FILE="school"

if [ -e $FILE ]
then
        echo " school file exists "
        if [ -s $FILE ]
        echo " school file is empty "
        else
                echo " school file is not empty "
        fi
        if [ -f $FILE ]
        then
                echo [ -f $FILE ]
        then
                echo  " school file is a regular file "
        fi
        else
		echo " school file does not exist "
	fi 

done
